/* @flow */

export const ASTTypes: Object = {
  Program: "Program",
  TypeAlias: "TypeAlias",
  ImportSpecifier: "ImportSpecifier",
  ImportDefaultSpecifier: "ImportDefaultSpecifier",
  ImportDeclaration: "ImportDeclaration",
  Identifier: "Identifier",
  StringLiteral: "StringLiteral",
  NumbericLiteral: "NumbericLiteral",
  BooleanLiteral: "BooleanLiteral",
  BinaryExpression: "BinaryExpression",
  ExportNamedDeclaration: "ExportNamedDeclaration",
  VariableDeclaration: "VariableDeclaration",
  VariableDeclarator: "VariableDeclarator",
  Identifier: "Identifier",
  ObjectExpression: "ObjectExpression",
  ObjectProperty: "ObjectProperty",
  ObjectMethod: "ObjectMethod",
  ObjectTypeAnnotation: "ObjectTypeAnnotation",
  ObjectTypeProperty: "ObjectTypeProperty",
  ExportDefaultDeclaration: "ExportDefaultDeclaration",
  CallExpression: "CallExpression",
  ClassDeclaration: "ClassDeclaration",
  TypeAnnotation: "TypeAnnotation",
  StringTypeAnnotation: "StringTypeAnnotation",
  NumberTypeAnnotation: "NumberTypeAnnotation",
  BooleanTypeAnnotation: "BooleanTypeAnnotation",
  GenericTypeAnnotation: "GenericTypeAnnotation",
  ClassProperty: "ClassProperty",
  ClassBody: "ClassBody",
  UnaryExpression: "UnaryExpression",
  CommentBlock: "CommentBlock",
  CommentLine: "CommentLine"
};
